export const BRIDGE_API_GROUPS = [
  {
    title: "Система и manifest",
    methods: [
      "bridge.catalog",
      "system.context",
      "system.openUrl",
      "system.openPath",
      "system.revealPath",
      "logs.write",
      "logs.list",
      "manifest.get",
      "manifest.update",
      "permissions.list",
      "permissions.ensure",
      "permissions.revoke",
      "network.hosts",
      "network.allowHost",
      "network.revokeHost",
      "widgets.list",
      "widgets.upsert",
      "widgets.delete",
      "actions.list",
      "actions.upsert",
      "actions.delete",
    ],
  },
  {
    title: "Агентный runtime",
    methods: [
      "agent.ask",
      "agent.startTopic",
      "agent.task",
      "agent.stream",
      "agent.streamAbort",
    ],
  },
  {
    title: "Данные app и файлы",
    methods: [
      "storage.get",
      "storage.set",
      "storage.list",
      "storage.delete",
      "fs.read",
      "fs.list",
      "fs.write",
      "fs.delete",
    ],
  },
  {
    title: "Проекты и топики",
    methods: [
      "projects.list",
      "projects.open",
      "project.profile.update",
      "project.sandbox.set",
      "project.apps.link",
      "project.apps.unlink",
      "topics.list",
      "topics.open",
      "skills.list",
      "project.skills.ensure",
      "project.skills.revoke",
      "mcp.servers",
      "project.mcp.upsert",
      "project.mcp.delete",
      "project.files.list",
      "project.files.read",
      "project.files.search",
      "project.files.write",
      "project.files.mkdir",
      "project.files.move",
      "project.files.copy",
      "project.files.delete",
    ],
  },
  {
    title: "Браузерный sidecar",
    methods: [
      "browser.init",
      "project.browser.setEnabled",
      "browser.tabs.list",
      "browser.open",
      "browser.close",
      "browser.setActive",
      "browser.navigate",
      "browser.back",
      "browser.forward",
      "browser.reload",
      "browser.currentUrl",
      "browser.readText",
      "browser.readOutline",
      "browser.screenshot",
      "browser.clickText",
      "browser.clickSelector",
      "browser.fill",
      "browser.scroll",
      "browser.waitFor",
    ],
  },
  {
    title: "Нативный macOS",
    methods: [
      "clipboard.readText",
      "clipboard.writeText",
      "dialog.openDirectory",
      "dialog.openFile",
      "dialog.saveFile",
      "notify.show",
    ],
  },
  {
    title: "Сеть",
    methods: ["net.fetch"],
  },
  {
    title: "Память",
    methods: [
      "memory.save",
      "memory.read",
      "memory.update",
      "memory.list",
      "memory.delete",
      "memory.search",
      "memory.recall",
      "memory.stats",
      "memory.reindex",
      "memory.indexPath",
      "memory.pathStatus",
      "memory.pathStatusBatch",
      "memory.forgetPath",
    ],
  },
  {
    title: "Автоматизации",
    methods: [
      "scheduler.list",
      "scheduler.upsert",
      "scheduler.delete",
      "scheduler.runNow",
      "scheduler.setPaused",
      "scheduler.runs",
      "scheduler.stats",
      "scheduler.runDetail",
    ],
  },
  {
    title: "Сетка apps",
    methods: [
      "events.emit",
      "events.subscribe",
      "events.unsubscribe",
      "events.subscriptions",
      "events.recent",
      "events.clearSubscriptions",
      "apps.list",
      "apps.create",
      "apps.export",
      "apps.import",
      "apps.delete",
      "apps.trashList",
      "apps.restore",
      "apps.purge",
      "apps.status",
      "apps.diff",
      "apps.commit",
      "apps.commitPartial",
      "apps.revert",
      "apps.server.status",
      "apps.server.logs",
      "apps.server.start",
      "apps.server.stop",
      "apps.server.restart",
      "apps.open",
      "apps.invoke",
      "apps.list_actions",
    ],
  },
] as const;

export const BRIDGE_HELPER_GROUPS = [
  {
    title: "База",
    helpers: [
      "reflexInvoke",
      "reflexBridgeCatalog",
      "reflexSystemContext",
      "reflexSystemOpenUrl",
      "reflexSystemOpenPath",
      "reflexSystemRevealPath",
      "reflexLog",
      "reflexLogList",
      "reflexManifestGet",
      "reflexManifestUpdate",
      "reflexPermissionsList",
      "reflexPermissionsEnsure",
      "reflexPermissionsRevoke",
      "reflexNetworkHosts",
      "reflexNetworkAllowHost",
      "reflexNetworkRevokeHost",
      "reflexWidgetsList",
      "reflexWidgetsUpsert",
      "reflexWidgetsDelete",
      "reflexActionsList",
      "reflexActionsUpsert",
      "reflexActionsDelete",
      "reflexCapabilities",
    ],
  },
  {
    title: "Агент",
    helpers: [
      "reflexAgentAsk",
      "reflexAgentStartTopic",
      "reflexAgentTask",
      "reflexAgentStream",
      "reflexAgentStreamAbort",
    ],
  },
  {
    title: "Хранилище / IO",
    helpers: [
      "reflexStorageGet",
      "reflexStorageSet",
      "reflexStorageList",
      "reflexStorageDelete",
      "reflexFsRead",
      "reflexFsList",
      "reflexFsWrite",
      "reflexFsDelete",
      "reflexClipboardReadText",
      "reflexClipboardWriteText",
      "reflexNetFetch",
      "reflexNotifyShow",
      "reflexDialogOpenDirectory",
      "reflexDialogOpenFile",
      "reflexDialogSaveFile",
    ],
  },
  {
    title: "Проекты / браузер",
    helpers: [
      "reflexProjectsList",
      "reflexProjectsOpen",
      "reflexProjectProfileUpdate",
      "reflexProjectSandboxSet",
      "reflexProjectAppsLink",
      "reflexProjectAppsUnlink",
      "reflexTopicsList",
      "reflexTopicsOpen",
      "reflexSkillsList",
      "reflexProjectSkillsEnsure",
      "reflexProjectSkillsRevoke",
      "reflexMcpServers",
      "reflexProjectMcpUpsert",
      "reflexProjectMcpDelete",
      "reflexProjectFilesList",
      "reflexProjectFilesRead",
      "reflexProjectFilesSearch",
      "reflexProjectFilesWrite",
      "reflexProjectFilesMkdir",
      "reflexProjectFilesMove",
      "reflexProjectFilesCopy",
      "reflexProjectFilesDelete",
      "reflexBrowserInit",
      "reflexProjectBrowserSetEnabled",
      "reflexBrowserTabs",
      "reflexBrowserOpen",
      "reflexBrowserClose",
      "reflexBrowserSetActive",
      "reflexBrowserNavigate",
      "reflexBrowserBack",
      "reflexBrowserForward",
      "reflexBrowserReload",
      "reflexBrowserCurrentUrl",
      "reflexBrowserReadText",
      "reflexBrowserReadOutline",
      "reflexBrowserScreenshot",
      "reflexBrowserClickText",
      "reflexBrowserClickSelector",
      "reflexBrowserFill",
      "reflexBrowserScroll",
      "reflexBrowserWaitFor",
    ],
  },
  {
    title: "Память / автоматизации / утилиты",
    helpers: [
      "reflexMemorySave",
      "reflexMemoryRead",
      "reflexMemoryUpdate",
      "reflexMemoryList",
      "reflexMemoryDelete",
      "reflexMemorySearch",
      "reflexMemoryRecall",
      "reflexMemoryStats",
      "reflexMemoryReindex",
      "reflexMemoryIndexPath",
      "reflexMemoryPathStatus",
      "reflexMemoryPathStatusBatch",
      "reflexMemoryForgetPath",
      "reflexSchedulerList",
      "reflexSchedulerUpsert",
      "reflexSchedulerDelete",
      "reflexSchedulerRunNow",
      "reflexSchedulerSetPaused",
      "reflexSchedulerRuns",
      "reflexSchedulerStats",
      "reflexSchedulerRunDetail",
      "reflexAppsList",
      "reflexAppsCreate",
      "reflexAppsExport",
      "reflexAppsImport",
      "reflexAppsDelete",
      "reflexAppsTrashList",
      "reflexAppsRestore",
      "reflexAppsPurge",
      "reflexAppsStatus",
      "reflexAppsDiff",
      "reflexAppsCommit",
      "reflexAppsCommitPartial",
      "reflexAppsRevert",
      "reflexAppsServerStatus",
      "reflexAppsServerLogs",
      "reflexAppsServerStart",
      "reflexAppsServerStop",
      "reflexAppsServerRestart",
      "reflexAppsOpen",
      "reflexAppsInvoke",
      "reflexAppsListActions",
      "reflexEventOn",
      "reflexEventOff",
      "reflexEventEmit",
      "reflexEventRecent",
      "reflexEventSubscriptions",
      "reflexEventClearSubscriptions",
    ],
  },
] as const;

export const BRIDGE_RECIPE_CARDS = [
  {
    title: "Контекстный sub-agent",
    body: "Project cwd подключает sandbox, MCP, preferred skills, project profile и memory/RAG.",
    calls: ["agent.task", "project.sandbox.set", "mcp.servers"],
    example: 'await reflexProjectSandboxSet({ projectId, sandbox: "workspace-write" });',
  },
  {
    title: "Долгая память",
    body: "Сохраняй новые факты и обновляй известный relPath без дублей.",
    calls: ["memory.save", "memory.update", "reflexMemoryUpdate"],
    example: 'await reflexMemoryUpdate("facts/user.md", { body, tags: ["profile"] });',
  },
  {
    title: "Возможности",
    body: "Добавляй permissions и network hosts точечно, без ручного слияния manifest.",
    calls: ["permissions.ensure", "network.allowHost", "reflexCapabilities"],
    example: 'await reflexNetworkAllowHost("api.example.com");',
  },
  {
    title: "Утилита как сервис",
    body: "Публикуй actions/widgets, создавай утилиты, экспортируй bundles и управляй server runtime.",
    calls: ["actions.upsert", "apps.create", "apps.export", "apps.server.status"],
    example: 'await reflexAppsCreate("утилита для ежедневного отчета");',
  },
  {
    title: "Автоматизация",
    body: "Schedule steps используют тот же bridge, кроме UI-only методов.",
    calls: ["scheduler.upsert", "scheduler.runs", "agent.task"],
    example: "await reflexSchedulerUpsert({ id, cron, steps });",
  },
  {
    title: "Дашборд здоровья",
    body: "Показывай состояние автоматизаций, RAG индекса и последнюю ошибку; для общего обзора добавь scheduler.read:*.",
    calls: ["scheduler.stats", "memory.stats", "widgets.upsert"],
    example:
      "const [jobs, memory] = await Promise.all([reflexSchedulerStats({ includeAll: true }), reflexMemoryStats({ projectId })]);",
  },
  {
    title: "Файлы проекта",
    body: "Ищи, правь и переиндексируй файлы linked project через bridge, не выходя из sandbox утилиты.",
    calls: ["project.files.search", "project.files.write", "memory.indexPath"],
    example:
      "const hits = await reflexProjectFilesSearch({ projectId, query, includeContent: true });",
  },
  {
    title: "Ревизии утилиты",
    body: "Показывай diff generated app, сохраняй осмысленные ревизии и откатывай неудачные правки.",
    calls: ["apps.diff", "apps.commitPartial", "apps.revert"],
    example: "const { diff } = await reflexAppsDiff(appId);",
  },
  {
    title: "Сетка событий",
    body: "Связывай утилиты через topics, recent history и подписки без прямых зависимостей между ними.",
    calls: ["events.emit", "events.subscribe", "events.recent"],
    example: 'reflexEventOn("ops.health", (event) => render(event.payload));',
  },
  {
    title: "Браузерный sidecar",
    body: "Включай project Browser MCP, открывай страницы, читай outline и заполняй формы.",
    calls: ["project.browser.setEnabled", "browser.open", "browser.fill"],
    example: "await reflexProjectBrowserSetEnabled({ projectId, enabled: true });",
  },
  {
    title: "MCP и skills проекта",
    body: "Обновляй project profile, закрепляй skills и подключай MCP servers с явными grants.",
    calls: ["project.profile.update", "project.skills.ensure", "project.mcp.upsert"],
    example:
      'await reflexProjectProfileUpdate({ description: "Agent workspace for growth loops" });',
  },
] as const;
