export const BRIDGE_API_GROUPS = [
  {
    title: "Система и manifest",
    methods: [
      "system.context",
      "system.openUrl",
      "system.openPath",
      "system.revealPath",
      "logs.write",
      "manifest.get",
      "manifest.update",
    ],
  },
  {
    title: "Агентный runtime",
    methods: [
      "agent.ask",
      "agent.startTopic",
      "agent.task",
      "agent.stream",
      "agent.streamAbort",
    ],
  },
  {
    title: "Данные app и файлы",
    methods: [
      "storage.get",
      "storage.set",
      "storage.list",
      "storage.delete",
      "fs.read",
      "fs.list",
      "fs.write",
      "fs.delete",
    ],
  },
  {
    title: "Проекты и топики",
    methods: [
      "projects.list",
      "projects.open",
      "topics.list",
      "topics.open",
      "skills.list",
      "mcp.servers",
    ],
  },
  {
    title: "Browser sidecar",
    methods: [
      "browser.init",
      "browser.tabs.list",
      "browser.open",
      "browser.navigate",
      "browser.readText",
      "browser.readOutline",
      "browser.screenshot",
      "browser.clickText",
      "browser.clickSelector",
      "browser.fill",
    ],
  },
  {
    title: "Нативный macOS",
    methods: [
      "clipboard.readText",
      "clipboard.writeText",
      "dialog.openDirectory",
      "dialog.openFile",
      "dialog.saveFile",
      "notify.show",
    ],
  },
  {
    title: "Сеть",
    methods: ["net.fetch"],
  },
  {
    title: "Память",
    methods: [
      "memory.save",
      "memory.read",
      "memory.update",
      "memory.list",
      "memory.delete",
      "memory.search",
      "memory.recall",
      "memory.indexPath",
      "memory.pathStatus",
      "memory.forgetPath",
    ],
  },
  {
    title: "Автоматизации",
    methods: [
      "scheduler.list",
      "scheduler.runNow",
      "scheduler.setPaused",
      "scheduler.runs",
      "scheduler.runDetail",
    ],
  },
  {
    title: "Сетка apps",
    methods: [
      "events.emit",
      "events.subscribe",
      "events.unsubscribe",
      "apps.list",
      "apps.open",
      "apps.invoke",
      "apps.list_actions",
    ],
  },
] as const;

export const BRIDGE_HELPER_GROUPS = [
  {
    title: "Core",
    helpers: [
      "reflexInvoke",
      "reflexSystemContext",
      "reflexSystemOpenUrl",
      "reflexSystemOpenPath",
      "reflexSystemRevealPath",
      "reflexLog",
      "reflexManifestGet",
      "reflexManifestUpdate",
      "reflexCapabilities",
    ],
  },
  {
    title: "Agent",
    helpers: [
      "reflexAgentAsk",
      "reflexAgentStartTopic",
      "reflexAgentTask",
      "reflexAgentStream",
      "reflexAgentStreamAbort",
    ],
  },
  {
    title: "Storage / IO",
    helpers: [
      "reflexStorageGet",
      "reflexStorageSet",
      "reflexStorageList",
      "reflexStorageDelete",
      "reflexFsRead",
      "reflexFsList",
      "reflexFsWrite",
      "reflexFsDelete",
      "reflexClipboardReadText",
      "reflexClipboardWriteText",
      "reflexNetFetch",
      "reflexNotifyShow",
      "reflexDialogOpenDirectory",
      "reflexDialogOpenFile",
      "reflexDialogSaveFile",
    ],
  },
  {
    title: "Projects / Browser",
    helpers: [
      "reflexProjectsList",
      "reflexProjectsOpen",
      "reflexTopicsList",
      "reflexTopicsOpen",
      "reflexSkillsList",
      "reflexMcpServers",
      "reflexBrowserInit",
      "reflexBrowserTabs",
      "reflexBrowserOpen",
      "reflexBrowserNavigate",
      "reflexBrowserReadText",
      "reflexBrowserReadOutline",
      "reflexBrowserScreenshot",
      "reflexBrowserClickText",
      "reflexBrowserClickSelector",
      "reflexBrowserFill",
    ],
  },
  {
    title: "Memory / Automation / Apps",
    helpers: [
      "reflexMemorySave",
      "reflexMemoryRead",
      "reflexMemoryUpdate",
      "reflexMemoryList",
      "reflexMemoryDelete",
      "reflexMemorySearch",
      "reflexMemoryRecall",
      "reflexMemoryIndexPath",
      "reflexMemoryPathStatus",
      "reflexMemoryForgetPath",
      "reflexSchedulerList",
      "reflexSchedulerRunNow",
      "reflexSchedulerSetPaused",
      "reflexSchedulerRuns",
      "reflexSchedulerRunDetail",
      "reflexAppsList",
      "reflexAppsOpen",
      "reflexAppsInvoke",
      "reflexAppsListActions",
      "reflexEventOn",
      "reflexEventOff",
      "reflexEventEmit",
    ],
  },
] as const;

export const BRIDGE_RECIPE_CARDS = [
  {
    title: "Контекстный sub-agent",
    body: "Project cwd подключает MCP, preferred skills, project profile и memory/RAG.",
    calls: ["agent.task", "reflexAgentTask", "mcp.servers"],
    example: "await reflexAgentTask({ prompt, cwd: projectRoot, memoryThreadId });",
  },
  {
    title: "Долгая память",
    body: "Сохраняй новые факты и обновляй известный relPath без дублей.",
    calls: ["memory.save", "memory.update", "reflexMemoryUpdate"],
    example: 'await reflexMemoryUpdate("facts/user.md", { body, tags: ["profile"] });',
  },
  {
    title: "App как сервис",
    body: "Публикуй manifest.actions и вызывай их из других apps или schedules.",
    calls: ["apps.invoke", "apps.list_actions", "events.emit"],
    example: 'await reflexAppsInvoke("health-stats", "today", {});',
  },
  {
    title: "Автоматизация",
    body: "Schedule steps используют тот же bridge, кроме UI-only методов.",
    calls: ["scheduler.runs", "agent.task", "notify.show"],
    example: 'steps: [{ method: "agent.task", params: { prompt } }]',
  },
  {
    title: "Browser sidecar",
    body: "Открывай страницу, читай текст/outline, кликай и заполняй формы.",
    calls: ["browser.open", "browser.readText", "browser.fill"],
    example: "const tab = await reflexBrowserOpen(url);",
  },
  {
    title: "MCP и skills проекта",
    body: "Покажи доступные skills и MCP names без раскрытия raw config.",
    calls: ["system.context", "skills.list", "mcp.servers"],
    example: "const ctx = await reflexSystemContext();",
  },
] as const;
